### PR TITLE
Last change time ago is added

### PR DESCRIPTION
**Pull request by tasomaniac**
Please review, feel free to change anything and merge. 

Here is how it looks like:

screen shot 2015-07-13 at 00 27 00

### CODE REVIEW

**Comment by tasomaniac** [comment]
Please review
@ulgens @atakangktepe @bilalyasar @demircancelebi

**Comment by ulgens** [comment]
:+1:

**Comment by bilalyasar** [comment]
so if we have update from 1 hour 15 min ago, your javascript will show a message like: `yaklasik 1 saat yaklasik 15 dakika once`, we need only 1 `yaklasik` i guess.

**Comment by tasomaniac** [comment]
I just get the javascript file from [here](http://uttesh.github.io/ngtimeago/) and translated the keywords into Turkish. :)
I think we are ok if I remove `yaklasik` words. 

Did you actually see `yaklasik 1 saat yaklasik 15 dakika once`? I think it shows only hours and it will be like `yaklasik 1 saat once`

**Comment by tasomaniac** [comment]
Thank you for reviewing guys. @bilalyasar @ulgens 

I will go ahead and merge this. I confirmed that it only shows hours. 

Feel free to improve it after merge.

**Pull request merged**
